let language = 'en';

if (localStorage.getItem("language")) {
    language = localStorage.getItem("language");
} else {
    localStorage.setItem("language", "en");
}

function lang() {
    return eval(language);
}

const en = {
    "language": "English, US",
    "page_home": "Home",
    "page_start": "Start",
    "page_explore": "Explore",
    "page_inbox": "Inbox",
    "page_settings": "Settings",
    "meo_username": "Username",
    "meo_password": "Password",
    "meo_messagebox": "What's on your mind?",
    "meo_goanywhere": "Where would you like to go?",
    "meo_bridged": {
        "start": "Bridged",
        "title": "This post has been bridged from another platform."
    },
    "title_chats": "Chats",
    "settings_general": "General",
    "settings_appearance": "Appearance",
    "settings_plugins": "Plugins",
    "settings_languages": "Languages",
    "general_sub": {
        "chat": "Chat",
        "accessibility": "Accessibility",
        "misc": "Miscellaneous",
        "acc": "Account",
        "blockedusers": "Blocks",
        "blockedwords": "Blacklisted Words",
        "about": "About",
        "credits": "Credits",
    },
    "general_list": {
        "title": {
            "homepage": "Auto-navigate to Home",
            "consolewarnings": "Disable console warning",
            "blockedmessages": "Hide blocked user messages",
            "invtyping": "Invisible typing",
            "imagewhitelist": "Allow images from any source",
            "censorwords": "Censor blacklisted words",
            "embeds": "Special embeds",
            "reducemotion": "Reduce motion",
            "showpostbuttons": "Always show post buttons",
            "underlinelinks": "Always underline links",
        },
        "desc": {
            "homepage": "Instead of showing you the Start Page you get directly taken to home",
            "consolewarnings": "Hides warning message from console",
            "blockedmessages": "Show a warning or hide messages completely",
            "invtyping": "Other users won't see you typing",
            "imagewhitelist": "This allows any site to see your IP, use responsibly",
            "censorwords": "Censors words instead of treating them like a blocked message",
            "embeds": "Embeds Tenor GIFS, Youtube Videos, ect. (Uses 3rd party cookies)",
            "reducemotion": "Reduce the intensity of animations and other moving effects",
            "showpostbuttons": "Post buttons always remain visible",
            "underlinelinks": "Make links to websites and other pages stand out more by underlining them",
        }
    },
    "appearance_sub": {
        "theme": "Theme",
        "spthemes": "Special Themes",
        "acthemes": "Accessible Themes",
        "ogthemes": "Original Themes",
        "glthemes": "Glass Themes",
        "cstheme": "Custom Theme",
        "cscss": "Custom CSS",
    },
    "plugins_sub": {
        "csplugin": "Custom Plugin",
    },
    "languages_sub": {
        "title": "Select a Language",
        "desc": "Don't see your language here? Help translate on",
    },
    "inbox_sub": {
        "desc": "Notifications are displayed here.",
    },
    "login_sub": {
        "title": "Login",
        "desc": "This client was made by eri :>",
        "oldpass": "Old Password",
        "newpass": "New Password",
    },
    "action": {
        "logout": "Log Out",
        "login": "Log In",
        "signup": "Register",
        "search": "Search",
        "mod": "Moderate",
        "creategc": "Create Chat",
        "dmme": "DM Me :)",
        "invite": "Invite People",
        "gohome": "Go Home",
        "cleartokens": "Clear Tokens",
        "changepw": "Change Password",
        "clearls": "Clear Localstorage",
        "deleteacc": "Delete Account",
        "block": "Block",
        "blockuser": "Block User",
        "blockword": "Blacklist Word",
        "run": "Run",
        "close": "Close",
        "back": "Back",
        "opennewtab": "Open in Browser",
        "reply": "Reply",
        "mention": "Mention",
        "report": "Report",
        "delete": "Delete",
        "edit": "Edit",
        "share": "Share",
        "comment": "Comment",
        "nick": "Nickname",
        "create": "Create",
        "reason": "Reason",
        "sendreport": "Send Report",
        "yes": "Yes",
        "confirm": "Confirm",
        "update": "Update",
        "go": "Go",
        "apply": "Apply",
        "savetheme": "Save Theme",
        "loadtheme": "Load Theme",
    },
    "info": {
        "accexists": "Username Already Taken!",
        "invaliduser": "Invalid Username!",
        "invalidpass": "Invalid Password!",
        "accbanned": "Account Banned!",
        "accdeleted": "Account Deleted!",
        "conflict": "You probably logged in on another client. Refresh the page and log back in to continue.",
        "unknown": "Unknown Login Status:",
        "chatremoved": "You have been removed from the chat you were in.",
        "passupdate": "Your password has been updated!",
        "editingpost": "Editing Post:",
        "reportsent": "Report Sent!",
        "blockedip": "Blocked IP",
        "searchany": "Search for anything!",
        "cleartokens": "This will log you out everywhere.",
        "clearls": "This will log you out.",
        "signup": "By signing up you agree to the Meower TOS",
        "tokenscleared": "Tokens deleted, you will need to log back in",
        "accscheduled": "Account scheduled for deletion",
        "deletewarn": "It will be deleted FOREVER (a very long time!)",
        "tryagain": "Try again",
        "cleared": "Cleared!",
        "plugin": "Restart now to apply new plugins and their settings",
    },
    "reports": {
        "spam": "Spam",
        "harrassment": "Harassment or abuse towards others",
        "language": "Rude, vulgar or offensive language",
        "nsfw": "NSFW (sexual, alcohol, violence, gore, etc.)",
        "scam": "Scams, hacks, phishing or other malicious content",
        "harm": "Threatening violence or real world harm",
        "illegal": "Illegal activity",
        "suicide": "Self-harm/suicide",
        "age": "This person is too young to use Meower",
        "other": "Other",
    },
    "modals": {
        "report": "Report Post",
        "blockword": "Blacklist a Word",
        "blockauser": "Block a User (case sensitive)",
        "blockuser": "Block",
        "unblockuser": "Unblock",
        "bgimage": "Background Image Link",
        "blockedip": "IP Blocked",
        "cleartokens": "Clear Tokens?",
        "changepass": "Change Password",
        "clearls": "Clear Localstorage?",
        "deleteacc": "Delete Account?",
        "share": "Share",
        "plugin": "Refresh Required!",
    },
    "profile": {
        "quote": "Quote",
        "persona": "Personalization",
        "proiflecolor": "Profile Color",
        "profilepic": "Profile Picture",
    },
}

const enuk = {
    "language": "English, UK",
    "page_home": "Home",
    "page_start": "Start",
    "page_explore": "Explore",
    "page_inbox": "Inbox",
    "page_settings": "Settings",
    "meo_username": "Username",
    "meo_password": "Password",
    "meo_messagebox": "What's on your mind?",
    "meo_goanywhere": "Where would you like to go?",
    "meo_bridged": {
        "start": "Bridged",
        "title": "This post has been bridged from another platform.",
    },
    "title_chats": "Chats",
    "settings_general": "General",
    "settings_appearance": "Appearance",
    "settings_plugins": "Plugins",
    "settings_languages": "Languages",
    "general_sub": {
        "chat": "Chat",
        "accessibility": "Accessibility",
        "misc": "Miscellaneous",
        "acc": "Account",
        "blockedusers": "Blocks",
        "blockedwords": "Blacklisted Words",
        "about": "About",
        "credits": "Credits",
    },
    "general_list": {
        "title": {
            "homepage": "Auto-navigate to Home",
            "consolewarnings": "Disable console warning",
            "blockedmessages": "Hide blocked user messages",
            "invtyping": "Invisible typing",
            "imagewhitelist": "Allow images from any source",
            "censorwords": "Censor blacklisted words",
            "embeds": "Special embeds",
            "reducemotion": "Reduce motion",
            "showpostbuttons": "Always show post buttons",
            "underlinelinks": "Always underline links",
        },
        "desc": {
            "homepage": "Instead of showing you the Start Page, you're taken directly to the Home.",
            "consolewarnings": "Hides warning messages from the console.",
            "blockedmessages": "Shows a warning or hides messages completely.",
            "invtyping": "Other users won't see you typing.",
            "imagewhitelist": "Allows images from any site, use responsibly.",
            "censorwords": "Censors words instead of treating them like a blocked message.",
            "embeds": "Embeds Tenor GIFs, YouTube Videos, etc. (Uses 3rd party cookies).",
            "reducemotion": "Reduces the intensity of animations and other moving effects.",
            "showpostbuttons": "Post buttons always remain visible.",
            "underlinelinks": "Makes links to websites and other pages stand out more by underlining them.",
        },
    },
    "appearance_sub": {
        "theme": "Theme",
        "spthemes": "Special Themes",
        "acthemes": "Accessible Themes",
        "ogthemes": "Original Themes",
        "glthemes": "Glass Themes",
        "cstheme": "Custom Theme",
        "cscss": "Custom CSS",
    },
    "plugins_sub": {
        "csplugin": "Custom Plugin"
    },
    "languages_sub": {
        "title": "Select a Language",
        "desc": "Don't see your language here? Help translate on",
    },
    "inbox_sub": {
        "desc": "Notifications are displayed here.",
    },
    "login_sub": {
        "title": "Login",
        "desc": "This client was made by eri :>",
        "oldpass": "Old Password",
        "newpass": "New Password",
    },
    "action": {
        "logout": "Log Out",
        "login": "Log In",
        "signup": "Register",
        "search": "Search",
        "mod": "Moderate",
        "creategc": "Create Chat",
        "dmme": "DM Me :)",
        "invite": "Invite People",
        "gohome": "Go Home",
        "cleartokens": "Clear Tokens",
        "changepw": "Change Password",
        "clearls": "Clear Local Storage",
        "deleteacc": "Delete Account",
        "block": "Block",
        "blockuser": "Block User",
        "blockword": "Blacklist Word",
        "run": "Run",
        "close": "Close",
        "back": "Back",
        "opennewtab": "Open in Browser",
        "reply": "Reply",
        "mention": "Mention",
        "report": "Report",
        "delete": "Delete",
        "edit": "Edit",
        "share": "Share",
        "comment": "Comment",
        "nick": "Nickname",
        "create": "Create",
        "reason": "Reason",
        "sendreport": "Send Report",
        "yes": "Yes",
        "confirm": "Confirm",
        "update": "Update",
        "go": "Go",
        "apply": "Apply",
        "savetheme": "Save Theme",
        "loadtheme": "Load Theme",
    },
    "info": {
        "accexists": "Username Already Taken!",
        "invaliduser": "Invalid Username!",
        "invalidpass": "Invalid Password!",
        "accbanned": "Account Banned!",
        "accdeleted": "Account Deleted!",
        "conflict": "You probably logged in on another client. Refresh the page and log back in to continue.",
        "unknown": "Unknown Login Status:",
        "chatremoved": "You have been removed from the chat you were in.",
        "passupdate": "Your password has been updated!",
        "editingpost": "Editing Post:",
        "reportsent": "Report Sent!",
        "blockedip": "Blocked IP",
        "searchany": "Search for anything!",
        "cleartokens": "This will log you out everywhere.",
        "clearls": "This will log you out.",
        "signup": "By signing up you agree to the Meower TOS",
        "tokenscleared": "Tokens deleted, you will need to log back in",
        "accscheduled": "Account scheduled for deletion",
        "deletewarn": "It will be deleted FOREVER (a very long time!)",
        "tryagain": "Try again",
        "cleared": "Cleared!",
        "plugin": "Restart now to apply new plugins and their settings",
    },
    "reports": {
        "spam": "Spam",
        "harassment": "Harassment or abuse towards others",
        "language": "Rude, vulgar or offensive language",
        "nsfw": "NSFW (sexual, alcohol, violence, gore, etc.)",
        "scam": "Scams, hacks, phishing or other malicious content",
        "harm": "Threatening violence or real world harm",
        "illegal": "Illegal activity",
        "suicide": "Self-harm/suicide",
        "age": "This person is too young to use Meower",
        "other": "Other",
    },
    "modals": {
        "report": "Report Post",
        "blockword": "Blacklist a Word",
        "blockauser": "Block a User (case sensitive)",
        "blockuser": "Block",
        "unblockuser": "Unblock",
        "bgimage": "Background Image Link",
        "blockedip": "IP Blocked",
        "cleartokens": "Clear Tokens?",
        "changepass": "Change Password",
        "clearls": "Clear Local Storage?",
        "deleteacc": "Delete Account?",
        "share": "Share",
        "plugin": "Refresh Required!",
    },
    "profile": {
        "quote": "Quote",
        "persona": "Personalisation",
        "proiflecolor": "Profile Colour",
        "profilepic": "Profile Picture",
    }
}