let language = 'en';

if (localStorage.getItem("language")) {
    language = localStorage.getItem("language");
} else {
    localStorage.setItem("language", "en");
}

function lang() {
    return eval(language);
}

const en = {
    "language": "English, US",
    "page_home": "Home",
    "page_start": "Start",
    "page_explore": "Explore",
    "page_inbox": "Inbox",
    "page_settings": "Settings",
    "meo_username": "Username",
    "meo_password": "Password",
    "meo_messagebox": "What's on your mind?",
    "meo_goanywhere": "Where would you like to go?",
    "meo_welcome": "Welcome!",
    "meo_bridged": {
        "start": "Bridged",
        "title": "This post has been bridged from another platform."
    },
    "title_chats": "Chats",
    "settings_general": "General",
    "settings_appearance": "Appearance",
    "settings_plugins": "Plugins",
    "settings_languages": "Languages",
    "general_sub": {
        "chat": "Chat",
        "accessibility": "Accessibility",
        "misc": "Miscellaneous",
        "acc": "Account",
        "blockedusers": "Blocks",
        "blockedwords": "Blacklisted Words",
        "about": "About",
        "credits": "Credits",
    },
    "general_list": {
        "title": {
            "homepage": "Auto-navigate to Home",
            "consolewarnings": "Disable console warning",
            "blockedmessages": "Hide blocked user messages",
            "invtyping": "Invisible typing",
            "imagewhitelist": "Allow images from any source",
            "censorwords": "Censor blacklisted words",
            "embeds": "Special embeds",
            "reducemotion": "Reduce motion",
            "showpostbuttons": "Always show post buttons",
            "underlinelinks": "Always underline links",
        },
        "desc": {
            "homepage": "Instead of showing you the Start Page you get directly taken to home",
            "consolewarnings": "Hides warning message from console",
            "blockedmessages": "Show a warning or hide messages completely",
            "invtyping": "Other users won't see you typing",
            "imagewhitelist": "This allows any site to see your IP, use responsibly",
            "censorwords": "Censors words instead of treating them like a blocked message",
            "embeds": "Embeds Tenor GIFS, Youtube Videos, ect. (Uses 3rd party cookies)",
            "reducemotion": "Reduce the intensity of animations and other moving effects",
            "showpostbuttons": "Post buttons always remain visible",
            "underlinelinks": "Make links to websites and other pages stand out more by underlining them",
        }
    },
    "appearance_sub": {
        "theme": "Theme",
        "spthemes": "Special Themes",
        "acthemes": "Accessible Themes",
        "ogthemes": "Original Themes",
        "glthemes": "Glass Themes",
        "cstheme": "Custom Theme",
        "cscss": "Custom CSS",
    },
    "plugins_sub": {
        "manage": "Manage",
    },
    "languages_sub": {
        "title": "Select a Language",
        "desc": "Don't see your language here? Help translate on",
        "link": "Github!"
    },
    "inbox_sub": {
        "desc": "Notifications are displayed here.",
    },
    "login_sub": {
        "title": "Login",
        "desc": "This client was made by eri :>",
        "oldpass": "Old Password",
        "newpass": "New Password",
    },
    "action": {
        "logout": "Log Out",
        "login": "Log In",
        "signup": "Register",
        "search": "Search",
        "mod": "Moderate",
        "creategc": "Create Chat",
        "dmme": "DM Me :)",
        "invite": "Invite People",
        "gohome": "Go Home",
        "cleartokens": "Clear Tokens",
        "changepw": "Change Password",
        "clearls": "Clear Localstorage",
        "deleteacc": "Delete Account",
        "block": "Block",
        "blockuser": "Block User",
        "blockword": "Blacklist Word",
        "run": "Run",
        "close": "Close",
        "back": "Back",
        "opennewtab": "Open in Browser",
        "reply": "Reply",
        "mention": "Mention",
        "report": "Report",
        "delete": "Delete",
        "edit": "Edit",
        "share": "Share",
        "comment": "Comment",
        "nick": "Nickname",
        "create": "Create",
        "reason": "Reason",
        "sendreport": "Send Report",
        "yes": "Yes",
        "confirm": "Confirm",
        "update": "Update",
        "go": "Go",
        "apply": "Apply",
        "savetheme": "Save Theme",
        "loadtheme": "Load Theme",
        "resetplugins": "Disable All",
    },
    "info": {
        "accexists": "Username Already Taken!",
        "invaliduser": "Invalid Username!",
        "invalidpass": "Invalid Password!",
        "accbanned": "Account Banned!",
        "accdeleted": "Account Deleted!",
        "conflict": "You probably logged in on another client. Refresh the page and log back in to continue.",
        "unknown": "Unknown Login Status:",
        "chatremoved": "You have been removed from the chat you were in.",
        "passupdate": "Your password has been updated!",
        "editingpost": "Editing Post:",
        "reportsent": "Report Sent!",
        "blockedip": "Blocked IP",
        "searchany": "Search for anything!",
        "cleartokens": "This will log you out everywhere.",
        "clearls": "This will log you out.",
        "signup": "By signing up you agree to the Meower TOS",
        "tokenscleared": "Tokens deleted, you will need to log back in",
        "accscheduled": "Account scheduled for deletion",
        "deletewarn": "It will be deleted FOREVER (a very long time!)",
        "tryagain": "Try again",
        "cleared": "Cleared!",
        "plugin": "Restart now to apply new plugins and their settings",
    },
    "reports": {
        "spam": "Spam",
        "harrassment": "Harassment or abuse towards others",
        "language": "Rude, vulgar or offensive language",
        "nsfw": "NSFW (sexual, alcohol, violence, gore, etc.)",
        "scam": "Scams, hacks, phishing or other malicious content",
        "harm": "Threatening violence or real world harm",
        "illegal": "Illegal activity",
        "suicide": "Self-harm/suicide",
        "age": "This person is too young to use Meower",
        "other": "Other",
    },
    "modals": {
        "report": "Report Post",
        "blockword": "Blacklist a Word",
        "blockauser": "Block a User (case sensitive)",
        "blockuser": "Block",
        "unblockuser": "Unblock",
        "bgimage": "Background Image Link",
        "blockedip": "IP Blocked",
        "cleartokens": "Clear Tokens?",
        "changepass": "Change Password",
        "clearls": "Clear Localstorage?",
        "deleteacc": "Delete Account?",
        "share": "Share",
        "plugin": "Refresh Required!",
    },
    "profile": {
        "quote": "Quote",
        "persona": "Personalization",
        "profilecolor": "Profile Color",
        "profilepic": "Profile Picture",
    },
}

const enuk = {
    "language": "English, UK",
    "page_home": "Home",
    "page_start": "Start",
    "page_explore": "Explore",
    "page_inbox": "Inbox",
    "page_settings": "Settings",
    "meo_username": "Username",
    "meo_password": "Password",
    "meo_messagebox": "What's on your mind?",
    "meo_goanywhere": "Where would you like to go?",
    "meo_welcome": "Welcome!",
    "meo_bridged": {
        "start": "Bridged",
        "title": "This post has been bridged from another platform.",
    },
    "title_chats": "Chats",
    "settings_general": "General",
    "settings_appearance": "Appearance",
    "settings_plugins": "Plugins",
    "settings_languages": "Languages",
    "general_sub": {
        "chat": "Chat",
        "accessibility": "Accessibility",
        "misc": "Miscellaneous",
        "acc": "Account",
        "blockedusers": "Blocks",
        "blockedwords": "Blacklisted Words",
        "about": "About",
        "credits": "Credits",
    },
    "general_list": {
        "title": {
            "homepage": "Auto-navigate to Home",
            "consolewarnings": "Disable console warning",
            "blockedmessages": "Hide blocked user messages",
            "invtyping": "Invisible typing",
            "imagewhitelist": "Allow images from any source",
            "censorwords": "Censor blacklisted words",
            "embeds": "Special embeds",
            "reducemotion": "Reduce motion",
            "showpostbuttons": "Always show post buttons",
            "underlinelinks": "Always underline links",
        },
        "desc": {
            "homepage": "Instead of showing you the Start Page, you're taken directly to the Home.",
            "consolewarnings": "Hides warning messages from the console.",
            "blockedmessages": "Shows a warning or hides messages completely.",
            "invtyping": "Other users won't see you typing.",
            "imagewhitelist": "Allows images from any site, use responsibly.",
            "censorwords": "Censors words instead of treating them like a blocked message.",
            "embeds": "Embeds Tenor GIFs, YouTube Videos, etc. (Uses 3rd party cookies).",
            "reducemotion": "Reduces the intensity of animations and other moving effects.",
            "showpostbuttons": "Post buttons always remain visible.",
            "underlinelinks": "Makes links to websites and other pages stand out more by underlining them.",
        },
    },
    "appearance_sub": {
        "theme": "Theme",
        "spthemes": "Special Themes",
        "acthemes": "Accessible Themes",
        "ogthemes": "Original Themes",
        "glthemes": "Glass Themes",
        "cstheme": "Custom Theme",
        "cscss": "Custom CSS",
    },
    "plugins_sub": {
        "manage": "Manage"
    },
    "languages_sub": {
        "title": "Select a Language",
        "desc": "Don't see your language here? Help translate on",
        "link": "Github!"
    },
    "inbox_sub": {
        "desc": "Notifications are displayed here.",
    },
    "login_sub": {
        "title": "Login",
        "desc": "This client was made by eri :>",
        "oldpass": "Old Password",
        "newpass": "New Password",
    },
    "action": {
        "logout": "Log Out",
        "login": "Log In",
        "signup": "Register",
        "search": "Search",
        "mod": "Moderate",
        "creategc": "Create Chat",
        "dmme": "DM Me :)",
        "invite": "Invite People",
        "gohome": "Go Home",
        "cleartokens": "Clear Tokens",
        "changepw": "Change Password",
        "clearls": "Clear Local Storage",
        "deleteacc": "Delete Account",
        "block": "Block",
        "blockuser": "Block User",
        "blockword": "Blacklist Word",
        "run": "Run",
        "close": "Close",
        "back": "Back",
        "opennewtab": "Open in Browser",
        "reply": "Reply",
        "mention": "Mention",
        "report": "Report",
        "delete": "Delete",
        "edit": "Edit",
        "share": "Share",
        "comment": "Comment",
        "nick": "Nickname",
        "create": "Create",
        "reason": "Reason",
        "sendreport": "Send Report",
        "yes": "Yes",
        "confirm": "Confirm",
        "update": "Update",
        "go": "Go",
        "apply": "Apply",
        "savetheme": "Save Theme",
        "loadtheme": "Load Theme",
        "resetplugins": "Disable All",
    },
    "info": {
        "accexists": "Username Already Taken!",
        "invaliduser": "Invalid Username!",
        "invalidpass": "Invalid Password!",
        "accbanned": "Account Banned!",
        "accdeleted": "Account Deleted!",
        "conflict": "You probably logged in on another client. Refresh the page and log back in to continue.",
        "unknown": "Unknown Login Status:",
        "chatremoved": "You have been removed from the chat you were in.",
        "passupdate": "Your password has been updated!",
        "editingpost": "Editing Post:",
        "reportsent": "Report Sent!",
        "blockedip": "Blocked IP",
        "searchany": "Search for anything!",
        "cleartokens": "This will log you out everywhere.",
        "clearls": "This will log you out.",
        "signup": "By signing up you agree to the Meower TOS",
        "tokenscleared": "Tokens deleted, you will need to log back in",
        "accscheduled": "Account scheduled for deletion",
        "deletewarn": "It will be deleted FOREVER (a very long time!)",
        "tryagain": "Try again",
        "cleared": "Cleared!",
        "plugin": "Restart now to apply new plugins and their settings",
    },
    "reports": {
        "spam": "Spam",
        "harassment": "Harassment or abuse towards others",
        "language": "Rude, vulgar or offensive language",
        "nsfw": "NSFW (sexual, alcohol, violence, gore, etc.)",
        "scam": "Scams, hacks, phishing or other malicious content",
        "harm": "Threatening violence or real world harm",
        "illegal": "Illegal activity",
        "suicide": "Self-harm/suicide",
        "age": "This person is too young to use Meower",
        "other": "Other",
    },
    "modals": {
        "report": "Report Post",
        "blockword": "Blacklist a Word",
        "blockauser": "Block a User (case sensitive)",
        "blockuser": "Block",
        "unblockuser": "Unblock",
        "bgimage": "Background Image Link",
        "blockedip": "IP Blocked",
        "cleartokens": "Clear Tokens?",
        "changepass": "Change Password",
        "clearls": "Clear Local Storage?",
        "deleteacc": "Delete Account?",
        "share": "Share",
        "plugin": "Refresh Required!",
    },
    "profile": {
        "quote": "Quote",
        "persona": "Personalisation",
        "profilecolor": "Profile Colour",
        "profilepic": "Profile Picture",
    }
}

const es = {
    //Spanish Translation by ethernet/Ethernet0
    //Last updated 6/8/2024 - version I
    //hi eri! :)
    "language": "Spanish Americas",
    "page_home": "Home",
    "page_start": "Inicio",
    "page_explore": "Explorar",
    "page_inbox": "Buzón",
    "page_settings": "Configuracion",
    "meo_username": "Nombre de Usuario",
    "meo_password": "Contraseña",
    "meo_messagebox": "¿En qué estás pensando?",
    "meo_goanywhere": "A dónde le gustaría ir?",
    "meo_welcome": "¡Bienvenido!",
    "meo_bridged": {
        "start": "Puenteado",
        "title": "Este mensaje ha sido puenteado desde otra plataforma."
    },
    "title_chats": "Chats",
    "settings_general": "General",
    "settings_appearance": "Apariencia",
    "settings_plugins": "Plugins (expansiones)",
    "settings_languages": "Idiomas",
    "general_sub": {
        "chat": "Chat",
        "accessibility": "Accesibilidad",
        "misc": "Otros",
        "acc": "Cuenta",
        "blockedusers": "Usuarios Bloqueados",
        "blockedwords": "Palabras Bloqueadas",
        "about": "Acerca De",
        "credits": "Creditos",
    },
    "general_list": {
        "title": {
            "homepage": "Auto-navegar a Home",
            "consolewarnings": "Desactivar advertencias de la consola",
            "blockedmessages": "Hide blocked user messages",
            "invtyping": "Escritura/Tecleado invisible",
            "imagewhitelist": "Permitir imágenes de cualquier fuente",
            "censorwords": "Censurar palabras de la lista negra",
            "embeds": "Incorporaciones especiales",
            "reducemotion": "Reducir movimiento",
            "showpostbuttons": "Siempre mostrar botones en mensajes",
            "underlinelinks": "Siempre subrayar enlaces",
        },
        "desc": {
            "homepage": "En lugar de mostrarte la página de inicio, navegar directamente a home",
            "consolewarnings": "Oculta los mensajes de alerta de la consola",
            "blockedmessages": "Mostrar una advertencia (o) ocultar completamente los mensajes bloqueados",
            "invtyping": "Otros usuarios no te verán teclear",
            "imagewhitelist": "Esto permite que cualquier sitio vea tu direction IP, use responsibly",
            "censorwords": "Censurar palabras en lugar de tratarlas como un mensaje bloqueado",
            "embeds": "Incoroporar GIFs de Tenor, Videos de Youtube, ect. (Usa cookies de 3ª part)",
            "reducemotion": "Reducir la intensidad de las animaciones y otros efectos con movimiento",
            "showpostbuttons": "Los botones en las publicaciónes/mensajes permanecen siempre visibles",
            "underlinelinks": "Subrayar los enlaces a sitios web y otras páginas para que destaquen más.",
        }
    },
    "appearance_sub": {
        "theme": "Tema",
        "spthemes": "Temas Speciales",
        "acthemes": "Temas Accesibles",
        "ogthemes": "Temas Originales",
        "glthemes": "Temas de Vidrio",
        "cstheme": "Tema Personalizado",
        "cscss": "Código CSS personalizado",
    },
    "plugins_sub": {
        "manage": "Manage"
    },
    "languages_sub": {
        "title": "Select a Language",
        "desc": "Don't see your language here? Help translate on",
        "link": "Github!"
    },
    "inbox_sub": {
        "desc": "Las notificaciones aparecen aquí.",
    },
    "login_sub": {
        "title": "Iniciar sesión",
        "desc": "Este cliente/servicio fue hecho por eri :> - Traducido al español por ether",
        "oldpass": "Contraseña Anterior",
        "newpass": "Contraseña Nueva",
    },
    "action": {
        "logout": "Cerrar Sesión",
        "login": "Iniciar Sesión",
        "signup": "Registrarse",
        "search": "Búsqueda",
        "mod": "Moderar",
        "creategc": "Crear Chat (Grupo)",
        "dmme": "DM Me :)",
        "invite": "Invitar Personas",
        "gohome": "Ir a Home",
        "cleartokens": "Borrar Fichas de sesión (Tokens)",
        "changepw": "Cambiar Contraseña",
        "clearls": "Borrar Almacenamiento Local",
        "deleteacc": "Eliminar Cuenta",
        "block": "Bloquear",
        "blockuser": "Bloquear Usuario",
        "blockword": "Añadir Palabra a la Lista Negra",
        "run": "Run (Ejecutar)",
        "close": "Cerrar",
        "back": "Atrás",
        "opennewtab": "Abrir En Navegador Web",
        "reply": "Responder",
        "mention": "Mencionar Usuario",
        "report": "Denunciar",
        "delete": "Eliminar",
        "edit": "Editar",
        "share": "Compartir",
        "comment": "Comentar",
        "nick": "Sobrenombre",
        "create": "Crear",
        "reason": "Razón",
        "sendreport": "Enviar Denuncia",
        "yes": "Si",
        "confirm": "Confirmar",
        "update": "Actualizar",
        "go": "Ir",
        "apply": "Aplicar",
        "savetheme": "Save Theme (Salvar Tema)",
        "loadtheme": "Load Theme (Cargar Tema)",
        "resetplugins": "Disable All",
    },
    "info": {
        "accexists": "¡Nombre de Usuario ya Ocupado!",
        "invaliduser": "¡Nombre de Usuario Inválido!",
        "invalidpass": "¡Contraseña Inválida!",
        "accbanned": "¡Cuenta Vetada!",
        "accdeleted": "¡Cuenta eliminada!",
        "conflict": "Es probable que hayas iniciado una sesión en otro servicio/ciber cliente. Refresque la página y vuelva a iniciar una sesión para continuar.",
        "unknown": "Estado de inicio de sesión desconocido:",
        "chatremoved": "Has sido eliminado del chat/grupo en el que estabas.",
        "passupdate": "Su contraseña ha sido actualizada. Es posible que tenga que volver a iniciar su sesión.",
        "editingpost": "Editando Mensaje:",
        "reportsent": "¡Denuncia enviada!",
        "blockedip": "Dirección IP bloqueada",
        "searchany": "¡Busca cualquier cosa!",
        "cleartokens": "Esto cerrará tu sesión en todas partes",
        "clearls": "Esto cerrará tu sesión.",
        "signup": "Al registrarte aceptas los términos y condiciones de servicio de Meower",
        "tokenscleared": "Fichas de sesión (Session Tokens) eliminadas, tendrá que volver a iniciar sesión",
        "accscheduled": "Cuenta de usuario programada para su eliminación",
        "deletewarn": "Se borrará PARA SIEMPRE (¡Un tiempo muy largo!)",
        "tryagain": "Inténtalo de nuevo",
        "cleared": "¡Borrado!",
        "plugin": "Restart now to apply new plugins and their settings",
    },
    "reports": {
        "spam": "Spam (Basura)",
        "harassment": "Acoso o abuso hacia otras personas",
        "language": "Lenguaje grosero, vulgar (y/o) ofensivo",
        "nsfw": "NSFW (sexual, alcohol, violencia, sangriento, etc.)",
        "scam": "Estafas, hackeos, phishing (y/o) otros contenidos maliciosos",
        "harm": "Amenazas de violencia o daños en el mundo real",
        "illegal": "Actividad ilegal",
        "suicide": "Autolesión/suicidio",
        "age": "Esta persona es demasiado/a joven para usar Meower",
        "other": "Otro",
    },
    "modals": {
        "report": "Denunciar Mensaje",
        "blockword": "Añadir Palabra a la Lista Negra",
        "blockauser": "Block a User (case sensitive)",
        "blockuser": "Bloquear",
        "unblockuser": "Desbloquear",
        "bgimage": "Enlace de Imagen de Fondo (Background Image Link)",
        "blockedip": "Dirección IP bloqueada",
        "cleartokens": "Borrar Fichas de sesión (Tokens)?",
        "changepass": "Cambiar Contraseña",
        "clearls": "Borrar Almacenamiento Local?",
    },
    "profile": {
        "quote": "Cita de perfil",
        "persona": "Personalización",
        "profilecolor": "Color del perfil",
        "profilepic": "Foto de perfil",
    },
}